### ISSUE TITLE
The DJ training guide has no content

### ISSUE THREAD

**Issue by williamleuschner** [WITR-Radio/manuals#3]
I just haven't done it yet. Will update when it's done.

**Comment by williamleuschner** [comment]
Update: The DJ training guide now has content. I just don't have some of the images, because they didn't get extracted from the PDF properly. Anybody have a Word copy of the DJ training guide?

**Comment by NoahLutz** [comment]
Do you need the trainer or the trainee guide?

**Comment by williamleuschner** [comment]
The trainee guide. It’s the one that says “DJ Training Guide” on the cover. As an aside, these are very difficult to distinguish names…

**Comment by jasapple** [comment]
Just checked through my 'archive' and I don't have the DJ ones :(
They may be shared with Mike in Google drive or someone should have it there. I remember reviewing and editing it so it's somewhere accessible to Engineering.

Good Luck

**Comment by NoahLutz** [comment]
I believe Claire has it. I'll have her share it with you @williamleuschner

**Comment by williamleuschner** [comment]
I've added all of the missing images to the DJ training guide. All that's left are formatting and typographical things, so that should be it for this issue. Thanks for your help, @NoahLutz!
